import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import path from "path";
import fs from "fs";

// When login.html exists (generated by AI), serve it at the root path / so the
// V1 preview iframe shows the generated page instead of the Vue SPA scaffold.
function loginHtmlPlugin() {
  return {
    name: "vite-plugin-login-html",
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        if (req.url === "/") {
          const loginPath = path.join(process.cwd(), "login.html");
          if (fs.existsSync(loginPath)) {
            res.setHeader("Content-Type", "text/html");
            res.setHeader("Cache-Control", "no-cache");
            fs.createReadStream(loginPath).pipe(res);
            return;
          }
        }
        next();
      });
    },
    configurePreviewServer(server) {
      server.middlewares.use(async (req, res, next) => {
        if (req.url === "/") {
          const loginPath = path.join(process.cwd(), "login.html");
          if (fs.existsSync(loginPath)) {
            res.setHeader("Content-Type", "text/html");
            res.setHeader("Cache-Control", "no-cache");
            fs.createReadStream(loginPath).pipe(res);
            return;
          }
        }
        next();
      });
    },
  };
}

// Vite dev server port is taken from the PORT env var so the V1 backend
// (which assigns a unique port per project in 8000+) controls where each
// template instance listens. `host: true` binds 0.0.0.0 so the iframe
// preview can reach it.
export default defineConfig({
  plugins: [vue(), loginHtmlPlugin()],
  server: {
    host: true,
    port: Number(process.env.PORT) || 5173,
    strictPort: true,
  },
});
